name: CI

on:
  merge_group:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Remove cargo config for incremental builds
        run: rm -f .cargo/config.toml

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-nightly-${{ hashFiles('**/Cargo.toml') }}

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Cache rust modules
        uses: Swatinem/rust-cache@v2.0.1
        with:
          cache-on-failure: true
          shared-key: ubuntu-build

      - name: Build & run tests
        run: cargo test

      - name: Clippy
        run: cargo clippy

      - name: Rustfmt check
        run: cargo fmt --check
